### ISSUE TITLE
Can't use Blueprint

### ISSUE THREAD

**Issue by axel358** [sonnyp/Workbench#175]
![Screenshot from 2022-11-21 11-34-44](https://user-images.githubusercontent.com/72220889/203323248-86350af1-638d-4722-9b4c-f3aa740ac379.png)
When using xml everything seems to work fine, but when i switch to blueprint i get this

**Comment by sonnyp** [comment]
Please share:

* Menu -> About -> Troubleshooting -> Debugging Information

As well as operating system name/version

**Comment by axel358** [comment]
![Screenshot from 2022-11-22 08-52-45](https://user-images.githubusercontent.com/72220889/203331354-072a0315-8df0-48de-ba67-be8986ebe27f.png)

**Comment by axel358** [comment]
Arch Linux

**Comment by sonnyp** [comment]
Can you reproduce after launching Workbench from the terminal and share all logs?

```
flatpak run re.sonny.Workbench
```

**Comment by sonnyp** [comment]
This is fixed in Workbench 43.3

Let me know otherwise.

**Comment by axel358** [comment]
Hi, unfortunately seems like it still does not work. Now switching to blueprint doesnt do anything, the code on the editor stays on xml. When opening i can brievly see the above mentioned error and then disappears.

**Comment by axel358** [comment]
![Screenshot from 2023-01-28 07-38-25](https://user-images.githubusercontent.com/72220889/215267037-1d7905d0-c140-4153-b065-37f9e0254deb.png)

**Comment by sonnyp** [comment]
That's annoying, I'm sorry. Can you share your computer specs?

**Comment by axel358** [comment]
![Screenshot from 2023-01-28 08-41-57](https://user-images.githubusercontent.com/72220889/215269670-478c6c97-26d3-4242-84c3-dee94cb95571.png)
Is this enough?

**Comment by axel358** [comment]
Maybe my computer is just too slow to port from blueprint to xml and then render it live xd

**Comment by axel358** [comment]
We
![Screenshot from 2023-01-28 09-01-12](https://user-images.githubusercontent.com/72220889/215270576-ddb3b7d9-dbe6-43e9-af7b-4d48f2cf25e7.png)
Tried a very minimal inteface n no effect

**Comment by sonnyp** [comment]
Workbench preview is quite expensive for your device indeed.

I will make it work, but I'm afraid the “real-time” experience will never be very good on that device.

It's working ok with XML right? Any idea how long it takes between editing and refresh?

**Comment by axel358** [comment]
Around 1.25 seconds

**Comment by sonnyp** [comment]
The timeout error is fixed in `main`. Could you confirm you're now able to use Blueprint?

Instructions to build Workbench from source are here if needed: https://github.com/sonnyp/Workbench/blob/main/CONTRIBUTING.md

In addition, we can add option to disable real time preview, which should help on slower devices.  https://github.com/sonnyp/Workbench/issues/213

**Comment by axel358** [comment]
Sorry it was difficult to me to build it at home. I'll try the new release as soon as i'm able to. Thank u for taking the time to work on this

**Comment by sonnyp** [comment]
No problem, I understand. I closed it because I'm confident it's fixed, and I also added an option to disable real-time preview. 

Let me know when 44 is out :+1:
